Pages/Webstore/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Webshop.Data;
using Webshop.Models;

namespace Webshop.Pages.Webstore
{
    public class IndexModel : PageModel
    {
        private readonly AppDbContext database;
        private readonly AccessControl accessControl;

        public IndexModel(AppDbContext database, AccessControl accessControl)
        {
            this.database = database;
            this.accessControl = accessControl;
        }

        public List<Product> Products { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? SearchString { get; set; }
        public SelectList? CategoryList { get; set; }

        [BindProperty(SupportsGet = true)]
        public int? SelectedCategoryId { get; set; }

        //Pagination variables
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public int PageSize { get; set; } = 10;

        public Account_Product Account_Product { get; set; } = new Account_Product();

        public async Task OnGet(int pageId = 1)
        {
            CurrentPage = pageId;

            IQueryable<Category> categoryNameQuery = from c in database.Categories
                                                     orderby c.Name
                                                     select c;

            CategoryList = new SelectList(await categoryNameQuery.ToListAsync(), "Id", "Name");


            var product = from p in database.Products
                          select p;

            if (!string.IsNullOrEmpty(SearchString))
            {
                product = product.Where(b => b.Name.Contains(SearchString));
            }

            if (SelectedCategoryId != null)
            {
                product = product.Where(p => p.Category.Id == SelectedCategoryId);
            }

            int totalCount = await product.CountAsync();
            TotalPages = (int)Math.Ceiling((double)totalCount / PageSize);

            Products = await product.Skip((CurrentPage - 1) * PageSize).Take(PageSize).ToListAsync();
        }

        public async Task<IActionResult> OnPostFastPurchase(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await database.Products.FindAsync(id);

            if (product == null)
            {
                return NotFound();
            }
            else
            {
                var existingProduct = await database.Account_Products.FirstOrDefaultAsync(ap => ap.Product.Id == product.Id && ap.Account.ID == accessControl.LoggedInAccountID);

                if (existingProduct != null)
                {
                    existingProduct.Quantity += 1;
                }
                else
                {
                    Account_Product.Account = await database.Accounts.Where(a => a.ID == accessControl.LoggedInAccountID).FirstAsync();
                    Account_Product.Product = product;
                    Account_Product.Quantity = 1;

                    database.Account_Products.Add(Account_Product);
                }

                await database.SaveChangesAsync();
            }

            return RedirectToPage("/Webstore/Cart");
        }

        public IActionResult OnGetReset()
        {
            return Page();
        }
    }
}

Pages/Webstore/OrderConfirmation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Webshop.Data;

namespace Webshop.Pages.Webstore
{
    public class OrderConfirmationModel : PageModel
    {
        private readonly AppDbContext database;

        public OrderConfirmationModel(AppDbContext database)
        {
            this.database = database;
        }

        public decimal Sum { get; set; }

        public void OnGet()
        {
            if (TempData.ContainsKey("TotalPrice") && TempData != null)
            {
                string? tempSum = TempData["TotalPrice"] as string;

                if (tempSum != null)
                {
                    Sum = decimal.Parse(tempSum);
                }
                else
                {
                    Sum = 0;
                }
            }
            else
            {
                Sum = 0;
            }

            Response.Cookies.Delete("DiscountCode");
        }
    }
}

Pages/Webstore/Cart.cshtml
@page
@model Webshop.Pages.Webstore.CartModel

<h1>Varukorg</h1>
<table class="cart">
    @if (Model.Account_Products.Any())
    {
        <thead>
            <tr>
                <th></th>
                <th>Namn</th>
                <th>Antal</th>
                <th>Styckpris</th>
                <th colspan="2">Totalpris</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model.Account_Products)
            {
                <tr class="cart-item">
                    <td><img src="/Images/@product.Product.Image" class="cart-product-image" /></td>
                    <td>@product.Product.Name</td>
                    <td>@product.Quantity</td>
                    <td>@(product.Product.Price)kr</td>

                    @{
                        decimal totalPrice = Math.Round(product.Product.Price * product.Quantity, 2);
                    }

                    <td>@(totalPrice)kr</td>
                    <td>
                        <form method="post" class="remove-item-form" asp-page-handler="Delete">
                            <input type="hidden" name="productId" value="@product.Id" />
                            <input type="submit" value="❌" id="remove-button" />
                        </form>
                    </td>
                </tr>
            }
            <tr class="cart-footer">
                <td colspan="3"></td>
                <td>
                    <form method="post" class="checkout-form">
                        <input type="submit" value="Till kassan" id="order-button" />
                    </form>
                </td>
                <td class="@(Model.Discount != 0 ? "discount-applied" : "")">
                    @Math.Round(Model.Sum, 2)kr
                </td>
                <td class="last-cell">
                    <form method="post" class="clear-cart" asp-page-handler="ClearCart">
                        <input type="submit" value="Rensa varukorg" id="clear-cart-button" />
                    </form>
                </td>
            </tr>
        </tbody>
    }
    else
    {
        <tbody>
            <tr>
                <td>Din varukorg är tom</td>
            </tr>
        </tbody>
    }
</table>
@if (Model.Account_Products.Any())
{
    <div class="discount-form">
        <form>
            <p>
                <label for="discount-input" class="discount-label">Ange rabattkod:</label>
                <input type="text" id="discount-input" name="DiscountCode" />
                <input type="submit" id="discount-button" value="Uppdatera" />
            </p>
        </form>
    </div>
}

@* Programmet decodade inte svenska bokstäver när denna stil låg i site.css och vi hittade ingen lösning, därav ligger den här *@
<style>
    .discount-form:hover::after {
        content: "Ledtråd: Lärare på Teknikhögskolan.";
        color: blue;
        background-color: orange;
        border-radius: 3px;
        padding: 5px;
        font-weight: bold;
        font-size: 11px;
    }
</style>

Pages/Webstore/Details.cshtml
@page
@model Webshop.Pages.Webstore.DetailsModel
@{
}

<div class="product-detail">
    <h2>@Model.Product.Name</h2>
    <strong><p>Kategori: @Model.Product.Category.Name</p></strong>
    <img src="/Images/@Model.Product.Image" alt="bait image" class="details-product-image" />
    <p>@Model.Product.Description</p>
    <p class="price">@Model.Product.Price kr</p>

    <form method="post" class="add-to-cart-form">
        <input type="hidden" name="id" value="@Model.Product.Id">
        <label for="quantity">Antal:</label>
        <input type="number" name="quantity" id="quantity" value="1" min="1" />
        <input type="submit" value="Lägg till i varukorg" id="cart-button" />
    </form>
</div>

Pages/Webstore/Index.cshtml
@page
@model Webshop.Pages.Webstore.IndexModel
@{
    ViewBag.Title = "Beten";
}

<h1>@ViewBag.Title</h1>
<div class="search-options">
    <form class="search-filter">
        
            <label for="select-category">Filtrera på kategori:</label>
            <select id="select-category" asp-for="SelectedCategoryId" asp-items="Model.CategoryList" onchange="this.form.submit()">
                <option value="">All</option>
            </select>
            <label for="SearchString">Sök fiskedrag:</label>
            <input type="text" asp-for="SearchString" />
            <input type="submit" value="Sök" id="search-button" />
            <a asp-page="/Webstore/Index" id="clear-filter">Rensa filter</a>
        
    </form>
</div>
<div class="container">
    @foreach (var product in Model.Products)
    {
        <div class="bait-box">
            <a asp-page="/Webstore/Details" asp-route-id="@product.Id">
                <h3 class="product-name">@product.Name</h3>
                <img src="/Images/@product.Image" alt="bait image" class="product-image" />
                <p class="product-price">@(product.Price) :-</p>
            </a>
            <form method="post" asp-page-handler="FastPurchase">
                <input type="hidden" name="id" value="@product.Id">
                <input type="submit" value="Köp" id="quick-purchase" />
            </form>
        </div>
    }
</div>
<div class="page-navigation-div">
    @if (Model.CurrentPage > 1)
    {
        <form method="get" class="page-navigation-form">
            <input type="hidden" name="pageId" value="@(Model.CurrentPage - 1)" />
            <button type="submit" class="previous-page-button">Föregående Sida</button>
        </form>
    }
    else
    {
        <button type="button" class="previous-page-button" disabled>Föregående Sida</button>
    }

    @if (Model.CurrentPage < Model.TotalPages)
    {
        <form method="get" class="page-navigation-form">
            <input type="hidden" name="pageId" value="@(Model.CurrentPage + 1)" />
            <button type="submit" class="next-page-button">Nästa Sida</button>
        </form>
    }
    else
    {
        <button type="button" class="next-page-button" disabled>Nästa Sida</button>
    }
</div>

Pages/Webstore/OrderConfirmation.cshtml
@page
@model Webshop.Pages.Webstore.OrderConfirmationModel
@{
}

<div class="confirmation-div">
    <h1>TACK FÖR DIN BESTÄLLNING!</h1>
    <h2>Totalbelopp: @Math.Round(Model.Sum, 2)kr</h2>

    <form action="/Webstore/Index" class="confirmation-form">
        <button type="submit" class="confirmation-button">Återgå till butiksidan</button>
    </form>
</div>